# Generated by Django 5.0 on 2023-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
