# Generated by Django 5.0.2 on 2024-02-23 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(help_text='*Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password'),
        ),
    ]
