# Generated by Django 5.0.2 on 2024-02-19 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist_name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('POP_MUSIC', 'Pop Music'), ('JAZZ_MUSIC', 'Jazz Music'), ('RNB_MUSIC', 'R&B Music'), ('ROCK_MUSIC', 'Rock Music'), ('COUNTRY_MUSIC', 'Country Music'), ('DANCE_MUSIC', 'Dance Music'), ('HIP_HOP_MUSIC', 'Hip Hop Music'), ('OTHER_MUSIC', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
