# Generated by Django 5.0.2 on 2024-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_model1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
