# Generated by Django 5.0 on 2024-01-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='web.person'),
            preserve_default=False,
        ),
    ]
