# Generated by Django 5.0.2 on 2024-02-23 07:59

import django.core.validators
import fruitipedia.fruits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_alter_fruit_description_alter_fruit_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(error_messages={'unique': 'This field must be unique. Custom error message.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.fruits.validators.validate_only_letters], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
    ]
