# Generated by Django 5.0.3 on 2024-03-08 07:25

import custom_auth.accounts.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountuser',
            managers=[
                ('objects', custom_auth.accounts.managers.AccountUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='accountuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
