# Generated by Django 5.0 on 2023-12-16 19:20

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media/photos/', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
